name: React

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: React Setup
        uses: actions/setup-node@v1
        with: 
            node-version: 14.x

      - name: Check out code into the React module directory
        uses: actions/checkout@v2
        with:
          path: frontend

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Run a multi-line script
        run: npm run lint
